IF NOT EXISTS (SELECT * FROM DBO.SYSUSERS WHERE NAME = N'dev_vcdb' )
BEGIN
	CREATE USER [dev_vcdb] FOR LOGIN [dev_vcdb_login] WITH DEFAULT_SCHEMA=[dbo];
	GRANT ALTER, CONTROL, CREATE SEQUENCE, DELETE, EXECUTE, INSERT, REFERENCES, SELECT, UPDATE, VIEW CHANGE TRACKING, VIEW DEFINITION ON SCHEMA :: dbo TO [dev_vcdb]
END