//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.5009
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Schema;
using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью xsd, версия=2.0.50727.3038.
// 

namespace VitalChoice.Ecommerce.Domain.Entities.VeraCore.FilesSchema
{
    /// <remarks/>
    [GeneratedCode ("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory ("code")]
    [XmlType (AnonymousType = true)]
    [XmlRoot (Namespace = "", IsNullable = false)]
    public class PurchaseOrder {
        private PurchaseOrderBillToAddress billToAddressField;
        private string budgetMailerUIDField;
        private string campaignIDField;
        private string companyIDField;
        private string contactPhoneNumberField;

        private string costCenterIDField;

        private string costCenterNameField;
        private string customerPurchaseOrderNumberField;
        private string discountCodeField;
        private decimal discountPercentageField;
        private string expediteNote1Field;
        private string expediteOrderFlagField;

        private string freightCarrierField;

        private string freightCodeField;
        private string fromPartyField;
        private PurchaseOrderOrdByAddress ordByAddressField;
        private PurchaseOrderOrderVariable[] orderVariableField;
        private PurchaseOrderPaymentInfo paymentInfoField;
        private string preRegUserIDField;
        private string proMailPONumField;
        private string projectIDField;
        private DateTime purchaseOrderDateField;
        private PurchaseOrderPurchaseOrderItemDetail[] purchaseOrderItemDetailField;
        private string purchaseOrderNumberField;
        private string purchaseOrderTimeField;

        private string releaseControlNumberField;

        private string releaseDateField;
        private string responseMediaField;

        private string sWSFreightCodeDescField;
        private string sWSFreightCodeField;
        private string shipHandChargeField;
        private PurchaseOrderShipToAddress shipToAddressField;
        private string shippingInstructions1Field;

        private string specHandField;
        private decimal specialHandlingChargeField;

        private decimal taxPercentageField;
        private string thirdPartyAccountField;

        private string thirdPartyAddTypeField;
        private string vendorCustIDField;
        private string vendorIDField;
        private string viewField;
        private string wmsReleaseDateField;

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string FromParty
        {
            get { return fromPartyField; }
            set { fromPartyField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string VendorID
        {
            get { return vendorIDField; }
            set { vendorIDField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string VendorCustID
        {
            get { return vendorCustIDField; }
            set { vendorCustIDField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string CompanyID
        {
            get { return companyIDField; }
            set { companyIDField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string PurchaseOrderNumber
        {
            get { return purchaseOrderNumberField; }
            set { purchaseOrderNumberField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string CustomerPurchaseOrderNumber
        {
            get { return customerPurchaseOrderNumberField; }
            set { customerPurchaseOrderNumberField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string ProMailPONum
        {
            get { return proMailPONumField; }
            set { proMailPONumField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified, DataType = "date")]
        public DateTime PurchaseOrderDate
        {
            get { return purchaseOrderDateField; }
            set { purchaseOrderDateField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string PurchaseOrderTime
        {
            get { return purchaseOrderTimeField; }
            set { purchaseOrderTimeField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string ResponseMedia
        {
            get { return responseMediaField; }
            set { responseMediaField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string ProjectID
        {
            get { return projectIDField; }
            set { projectIDField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string View
        {
            get { return viewField; }
            set { viewField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string PreRegUserID
        {
            get { return preRegUserIDField; }
            set { preRegUserIDField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string ShipHandCharge
        {
            get { return shipHandChargeField; }
            set { shipHandChargeField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public PurchaseOrderPaymentInfo PaymentInfo
        {
            get { return paymentInfoField; }
            set { paymentInfoField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string ExpediteOrderFlag
        {
            get { return expediteOrderFlagField; }
            set { expediteOrderFlagField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string ExpediteNote1
        {
            get { return expediteNote1Field; }
            set { expediteNote1Field = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string CostCenterID
        {
            get { return costCenterIDField; }
            set { costCenterIDField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string CostCenterName
        {
            get { return costCenterNameField; }
            set { costCenterNameField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string FreightCarrier
        {
            get { return freightCarrierField; }
            set { freightCarrierField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string FreightCode
        {
            get { return freightCodeField; }
            set { freightCodeField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string ReleaseControlNumber
        {
            get { return releaseControlNumberField; }
            set { releaseControlNumberField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string ReleaseDate
        {
            get { return releaseDateField; }
            set { releaseDateField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string WmsReleaseDate
        {
            get { return wmsReleaseDateField; }
            set { wmsReleaseDateField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string BudgetMailerUID
        {
            get { return budgetMailerUIDField; }
            set { budgetMailerUIDField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string SWSFreightCode
        {
            get { return sWSFreightCodeField; }
            set { sWSFreightCodeField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string SWSFreightCodeDesc
        {
            get { return sWSFreightCodeDescField; }
            set { sWSFreightCodeDescField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string ThirdPartyAccount
        {
            get { return thirdPartyAccountField; }
            set { thirdPartyAccountField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string ThirdPartyAddType
        {
            get { return thirdPartyAddTypeField; }
            set { thirdPartyAddTypeField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string CampaignID
        {
            get { return campaignIDField; }
            set { campaignIDField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public decimal SpecialHandlingCharge
        {
            get { return specialHandlingChargeField; }
            set { specialHandlingChargeField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string SpecHand
        {
            get { return specHandField; }
            set { specHandField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public decimal TaxPercentage
        {
            get { return taxPercentageField; }
            set { taxPercentageField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public decimal DiscountPercentage
        {
            get { return discountPercentageField; }
            set { discountPercentageField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string DiscountCode
        {
            get { return discountCodeField; }
            set { discountCodeField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string ContactPhoneNumber
        {
            get { return contactPhoneNumberField; }
            set { contactPhoneNumberField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string ShippingInstructions1
        {
            get { return shippingInstructions1Field; }
            set { shippingInstructions1Field = value; }
        }

        /// <remarks/>
        [XmlElement ("OrderVariable", Form = XmlSchemaForm.Unqualified)]
        public PurchaseOrderOrderVariable[] OrderVariable
        {
            get { return orderVariableField; }
            set { orderVariableField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public PurchaseOrderShipToAddress ShipToAddress
        {
            get { return shipToAddressField; }
            set { shipToAddressField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public PurchaseOrderBillToAddress BillToAddress
        {
            get { return billToAddressField; }
            set { billToAddressField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public PurchaseOrderOrdByAddress OrdByAddress
        {
            get { return ordByAddressField; }
            set { ordByAddressField = value; }
        }

        /// <remarks/>
        [XmlElement ("PurchaseOrderItemDetail", Form = XmlSchemaForm.Unqualified)]
        public PurchaseOrderPurchaseOrderItemDetail[] PurchaseOrderItemDetail
        {
            get { return purchaseOrderItemDetailField; }
            set { purchaseOrderItemDetailField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode ("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory ("code")]
    [XmlType (AnonymousType = true)]
    public class PurchaseOrderPaymentInfo {
        private string cCExpDateField;
        private string cCNumberField;
        private string cCPayTypeCodeField;

        private string checkAmountField;
        private string giftCertificateField;

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string GiftCertificate
        {
            get { return giftCertificateField; }
            set { giftCertificateField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string CCPayTypeCode
        {
            get { return cCPayTypeCodeField; }
            set { cCPayTypeCodeField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string CCNumber
        {
            get { return cCNumberField; }
            set { cCNumberField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string CCExpDate
        {
            get { return cCExpDateField; }
            set { cCExpDateField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string CheckAmount
        {
            get { return checkAmountField; }
            set { checkAmountField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode ("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory ("code")]
    [XmlType (AnonymousType = true)]
    public class PurchaseOrderOrderVariable {
        private string ovFieldNameField;

        private string ovFieldValueField;

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string OvFieldName
        {
            get { return ovFieldNameField; }
            set { ovFieldNameField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string OvFieldValue
        {
            get { return ovFieldValueField; }
            set { ovFieldValueField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode ("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory ("code")]
    [XmlType (AnonymousType = true)]
    public class PurchaseOrderShipToAddress {
        private string addressIDField;

        private string attentionField;

        private string cityField;

        private string countryCodeField;
        private string emailField;
        private string faxField;

        private string insideDeliveryFlagField;
        private string internationalStateField;
        private string line1Field;

        private string line2Field;
        private string mailStopField;
        private PurchaseOrderShipToAddressMailerVariable[] mailerVariableField;

        private string markFor1Field;

        private string markFor2Field;
        private string nameField;

        private string phoneField;
        private string postalCodeField;
        private string stateProvinceCodeField;

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string AddressID
        {
            get { return addressIDField; }
            set { addressIDField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string Name
        {
            get { return nameField; }
            set { nameField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string Attention
        {
            get { return attentionField; }
            set { attentionField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string Line1
        {
            get { return line1Field; }
            set { line1Field = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string Line2
        {
            get { return line2Field; }
            set { line2Field = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string City
        {
            get { return cityField; }
            set { cityField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string StateProvinceCode
        {
            get { return stateProvinceCodeField; }
            set { stateProvinceCodeField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string PostalCode
        {
            get { return postalCodeField; }
            set { postalCodeField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string InternationalState
        {
            get { return internationalStateField; }
            set { internationalStateField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string CountryCode
        {
            get { return countryCodeField; }
            set { countryCodeField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string InsideDeliveryFlag
        {
            get { return insideDeliveryFlagField; }
            set { insideDeliveryFlagField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string MarkFor1
        {
            get { return markFor1Field; }
            set { markFor1Field = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string MarkFor2
        {
            get { return markFor2Field; }
            set { markFor2Field = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string MailStop
        {
            get { return mailStopField; }
            set { mailStopField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string Phone
        {
            get { return phoneField; }
            set { phoneField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string Fax
        {
            get { return faxField; }
            set { faxField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string Email
        {
            get { return emailField; }
            set { emailField = value; }
        }

        /// <remarks/>
        [XmlElement ("MailerVariable", Form = XmlSchemaForm.Unqualified)]
        public PurchaseOrderShipToAddressMailerVariable[] MailerVariable
        {
            get { return mailerVariableField; }
            set { mailerVariableField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode ("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory ("code")]
    [XmlType (AnonymousType = true)]
    public class PurchaseOrderShipToAddressMailerVariable {
        private string mvFieldNameField;

        private string mvFieldValueField;

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string MvFieldName
        {
            get { return mvFieldNameField; }
            set { mvFieldNameField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string MvFieldValue
        {
            get { return mvFieldValueField; }
            set { mvFieldValueField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode ("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory ("code")]
    [XmlType (AnonymousType = true)]
    public class PurchaseOrderBillToAddress {
        private string addressIDField;

        private string attentionField;

        private string cityField;

        private string countryCodeField;
        private string emailField;
        private string faxField;

        private string insideDeliveryFlagField;
        private string internationalStateField;
        private string line1Field;

        private string line2Field;
        private string mailStopField;
        private PurchaseOrderBillToAddressMailerVariable[] mailerVariableField;

        private string markFor1Field;

        private string markFor2Field;
        private string nameField;

        private string phoneField;
        private string postalCodeField;
        private string stateProvinceCodeField;

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string AddressID
        {
            get { return addressIDField; }
            set { addressIDField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string Name
        {
            get { return nameField; }
            set { nameField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string Attention
        {
            get { return attentionField; }
            set { attentionField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string Line1
        {
            get { return line1Field; }
            set { line1Field = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string Line2
        {
            get { return line2Field; }
            set { line2Field = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string City
        {
            get { return cityField; }
            set { cityField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string StateProvinceCode
        {
            get { return stateProvinceCodeField; }
            set { stateProvinceCodeField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string PostalCode
        {
            get { return postalCodeField; }
            set { postalCodeField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string InternationalState
        {
            get { return internationalStateField; }
            set { internationalStateField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string CountryCode
        {
            get { return countryCodeField; }
            set { countryCodeField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string InsideDeliveryFlag
        {
            get { return insideDeliveryFlagField; }
            set { insideDeliveryFlagField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string MarkFor1
        {
            get { return markFor1Field; }
            set { markFor1Field = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string MarkFor2
        {
            get { return markFor2Field; }
            set { markFor2Field = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string MailStop
        {
            get { return mailStopField; }
            set { mailStopField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string Phone
        {
            get { return phoneField; }
            set { phoneField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string Fax
        {
            get { return faxField; }
            set { faxField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string Email
        {
            get { return emailField; }
            set { emailField = value; }
        }

        /// <remarks/>
        [XmlElement ("MailerVariable", Form = XmlSchemaForm.Unqualified)]
        public PurchaseOrderBillToAddressMailerVariable[] MailerVariable
        {
            get { return mailerVariableField; }
            set { mailerVariableField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode ("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory ("code")]
    [XmlType (AnonymousType = true)]
    public class PurchaseOrderBillToAddressMailerVariable {
        private string mvFieldNameField;

        private string mvFieldValueField;

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string MvFieldName
        {
            get { return mvFieldNameField; }
            set { mvFieldNameField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string MvFieldValue
        {
            get { return mvFieldValueField; }
            set { mvFieldValueField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode ("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory ("code")]
    [XmlType (AnonymousType = true)]
    public class PurchaseOrderOrdByAddress {
        private string addressIDField;

        private string attentionField;

        private string cityField;

        private string countryCodeField;
        private string emailField;
        private string faxField;

        private string insideDeliveryFlagField;
        private string internationalStateField;
        private string line1Field;

        private string line2Field;
        private string mailStopField;
        private PurchaseOrderOrdByAddressMailerVariable[] mailerVariableField;

        private string markFor1Field;

        private string markFor2Field;
        private string nameField;

        private string phoneField;
        private string postalCodeField;
        private string stateProvinceCodeField;

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string AddressID
        {
            get { return addressIDField; }
            set { addressIDField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string Name
        {
            get { return nameField; }
            set { nameField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string Attention
        {
            get { return attentionField; }
            set { attentionField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string Line1
        {
            get { return line1Field; }
            set { line1Field = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string Line2
        {
            get { return line2Field; }
            set { line2Field = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string City
        {
            get { return cityField; }
            set { cityField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string StateProvinceCode
        {
            get { return stateProvinceCodeField; }
            set { stateProvinceCodeField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string PostalCode
        {
            get { return postalCodeField; }
            set { postalCodeField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string InternationalState
        {
            get { return internationalStateField; }
            set { internationalStateField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string CountryCode
        {
            get { return countryCodeField; }
            set { countryCodeField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string InsideDeliveryFlag
        {
            get { return insideDeliveryFlagField; }
            set { insideDeliveryFlagField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string MarkFor1
        {
            get { return markFor1Field; }
            set { markFor1Field = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string MarkFor2
        {
            get { return markFor2Field; }
            set { markFor2Field = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string MailStop
        {
            get { return mailStopField; }
            set { mailStopField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string Phone
        {
            get { return phoneField; }
            set { phoneField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string Fax
        {
            get { return faxField; }
            set { faxField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string Email
        {
            get { return emailField; }
            set { emailField = value; }
        }

        /// <remarks/>
        [XmlElement ("MailerVariable", Form = XmlSchemaForm.Unqualified)]
        public PurchaseOrderOrdByAddressMailerVariable[] MailerVariable
        {
            get { return mailerVariableField; }
            set { mailerVariableField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode ("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory ("code")]
    [XmlType (AnonymousType = true)]
    public class PurchaseOrderOrdByAddressMailerVariable {
        private string mvFieldNameField;

        private string mvFieldValueField;

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string MvFieldName
        {
            get { return mvFieldNameField; }
            set { mvFieldNameField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string MvFieldValue
        {
            get { return mvFieldValueField; }
            set { mvFieldValueField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode ("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory ("code")]
    [XmlType (AnonymousType = true)]
    public class PurchaseOrderPurchaseOrderItemDetail {
        private PurchaseOrderPurchaseOrderItemDetailAssemDetails[] assemDetailsField;
        private string clusterProductIDField;
        private string colorField;
        private string customerProductDescriptionField;
        private string customerProductIDField;

        private string docIDField;
        private string lineNumberField;

        private string offerInstructionsField;

        private PurchaseOrderPurchaseOrderItemDetailOfferVariable[] offerVariableField;
        private string orderQuantityField;
        private decimal sellPriceField;

        private string sizeField;
        private string unitOfMeasureField;
        private string vendorProductDescriptionField;
        private string vendorProductIDField;

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string LineNumber
        {
            get { return lineNumberField; }
            set { lineNumberField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string VendorProductID
        {
            get { return vendorProductIDField; }
            set { vendorProductIDField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string VendorProductDescription
        {
            get { return vendorProductDescriptionField; }
            set { vendorProductDescriptionField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string CustomerProductID
        {
            get { return customerProductIDField; }
            set { customerProductIDField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string CustomerProductDescription
        {
            get { return customerProductDescriptionField; }
            set { customerProductDescriptionField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified, DataType = "integer")]
        public string OrderQuantity
        {
            get { return orderQuantityField; }
            set { orderQuantityField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string UnitOfMeasure
        {
            get { return unitOfMeasureField; }
            set { unitOfMeasureField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public decimal SellPrice
        {
            get { return sellPriceField; }
            set { sellPriceField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string Size
        {
            get { return sizeField; }
            set { sizeField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string Color
        {
            get { return colorField; }
            set { colorField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string ClusterProductID
        {
            get { return clusterProductIDField; }
            set { clusterProductIDField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string DocID
        {
            get { return docIDField; }
            set { docIDField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string OfferInstructions
        {
            get { return offerInstructionsField; }
            set { offerInstructionsField = value; }
        }

        /// <remarks/>
        [XmlElement ("OfferVariable", Form = XmlSchemaForm.Unqualified)]
        public PurchaseOrderPurchaseOrderItemDetailOfferVariable[] OfferVariable
        {
            get { return offerVariableField; }
            set { offerVariableField = value; }
        }

        /// <remarks/>
        [XmlElement ("AssemDetails", Form = XmlSchemaForm.Unqualified)]
        public PurchaseOrderPurchaseOrderItemDetailAssemDetails[] AssemDetails
        {
            get { return assemDetailsField; }
            set { assemDetailsField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode ("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory ("code")]
    [XmlType (AnonymousType = true)]
    public class PurchaseOrderPurchaseOrderItemDetailOfferVariable {
        private string cstFieldField;

        private string cstValueField;

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string cstField
        {
            get { return cstFieldField; }
            set { cstFieldField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string cstValue
        {
            get { return cstValueField; }
            set { cstValueField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode ("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory ("code")]
    [XmlType (AnonymousType = true)]
    public class PurchaseOrderPurchaseOrderItemDetailAssemDetails {
        private string partNumberField;

        private string quantityField;

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified)]
        public string PartNumber
        {
            get { return partNumberField; }
            set { partNumberField = value; }
        }

        /// <remarks/>
        [XmlElement (Form = XmlSchemaForm.Unqualified, DataType = "integer")]
        public string Quantity
        {
            get { return quantityField; }
            set { quantityField = value; }
        }
    }
}