//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.5009
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью xsd, версия=2.0.50727.3038.
// 

namespace VitalChoice.Ecommerce.Domain.Entities.VeraCore.FilesSchema
{
    /// <remarks/>
    [GeneratedCode ("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory ("code")]
    [XmlType (AnonymousType = true)]
    [XmlRoot (Namespace = "", IsNullable = false)]
    public class PurchaseOrderAcknowledgment {
        private DateTime acknowledgmentDateField;
        private AcknowledgmentItemDetail[] acknowledgmentItemDetailField;

        private DateTime acknowledgmentTimeField;
        private AcknowledgmentType acknowledgmentTypeField;
        private string companyIDField;

        private string customerPurchaseOrderNumberField;

        private string fromField;
        private string orderRejectionMessageField;
        private DateTime purchaseOrderDateField;

        private bool purchaseOrderDateFieldSpecified;
        private string purchaseOrderNumberField;

        private string toField;
        private string vendorCustIDField;
        private string vendorIDField;

        /// <remarks/>
        public string VendorID
        {
            get { return vendorIDField; }
            set { vendorIDField = value; }
        }

        /// <remarks/>
        public string VendorCustID
        {
            get { return vendorCustIDField; }
            set { vendorCustIDField = value; }
        }

        /// <remarks/>
        public string CompanyID
        {
            get { return companyIDField; }
            set { companyIDField = value; }
        }

        /// <remarks/>
        public AcknowledgmentType AcknowledgmentType
        {
            get { return acknowledgmentTypeField; }
            set { acknowledgmentTypeField = value; }
        }

        /// <remarks/>
        [XmlElement (DataType = "date")]
        public DateTime AcknowledgmentDate
        {
            get { return acknowledgmentDateField; }
            set { acknowledgmentDateField = value; }
        }

        /// <remarks/>
        [XmlElement (DataType = "time")]
        public DateTime AcknowledgmentTime
        {
            get { return acknowledgmentTimeField; }
            set { acknowledgmentTimeField = value; }
        }

        /// <remarks/>
        public string PurchaseOrderNumber
        {
            get { return purchaseOrderNumberField; }
            set { purchaseOrderNumberField = value; }
        }

        /// <remarks/>
        [XmlElement (DataType = "date")]
        public DateTime PurchaseOrderDate
        {
            get { return purchaseOrderDateField; }
            set { purchaseOrderDateField = value; }
        }

        /// <remarks/>
        [XmlIgnore]
        public bool PurchaseOrderDateSpecified
        {
            get { return purchaseOrderDateFieldSpecified; }
            set { purchaseOrderDateFieldSpecified = value; }
        }

        /// <remarks/>
        public string CustomerPurchaseOrderNumber
        {
            get { return customerPurchaseOrderNumberField; }
            set { customerPurchaseOrderNumberField = value; }
        }

        /// <remarks/>
        public string OrderRejectionMessage
        {
            get { return orderRejectionMessageField; }
            set { orderRejectionMessageField = value; }
        }

        /// <remarks/>
        [XmlElement ("AcknowledgmentItemDetail")]
        public AcknowledgmentItemDetail[] AcknowledgmentItemDetail
        {
            get { return acknowledgmentItemDetailField; }
            set { acknowledgmentItemDetailField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string From
        {
            get { return fromField; }
            set { fromField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string To
        {
            get { return toField; }
            set { toField = value; }
        }
    }

    /// <remarks/>
    [Flags]
    [GeneratedCode ("xsd", "2.0.50727.3038")]
    [Serializable]
    [XmlType (AnonymousType = true)]
    [XmlRoot (Namespace = "", IsNullable = false)]
    public enum AcknowledgmentType {
        /// <remarks/>
        AC = 1,

        /// <remarks/>
        IA = 2,

        /// <remarks/>
        IB = 4,

        /// <remarks/>
        IC = 8,

        /// <remarks/>
        IR = 16,
    }

    /// <remarks/>
    [GeneratedCode ("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory ("code")]
    [XmlType (AnonymousType = true)]
    [XmlRoot (Namespace = "", IsNullable = false)]
    public class AcknowledgmentItemDetail {
        private string acknowledgedQuantityField;

        private decimal acknowledgedSellPriceField;
        private string acknowledgedUnitOfMeasureField;
        private string customerProductIDField;
        private ItemAcknowledgmentType itemAcknowledgmentTypeField;
        private string itemRejectionMessageField;
        private string lineNumberField;
        private string orderQuantityField;
        private string replacedProductIDField;

        private DateTime scheduledToShipDateField;

        private bool scheduledToShipDateFieldSpecified;
        private decimal sellPriceField;
        private string substitutedProductIDField;
        private string unitOfMeasureField;
        private string vendorProductIDField;

        /// <remarks/>
        [XmlElement (DataType = "integer")]
        public string LineNumber
        {
            get { return lineNumberField; }
            set { lineNumberField = value; }
        }

        /// <remarks/>
        public ItemAcknowledgmentType ItemAcknowledgmentType
        {
            get { return itemAcknowledgmentTypeField; }
            set { itemAcknowledgmentTypeField = value; }
        }

        /// <remarks/>
        public string VendorProductID
        {
            get { return vendorProductIDField; }
            set { vendorProductIDField = value; }
        }

        /// <remarks/>
        public string CustomerProductID
        {
            get { return customerProductIDField; }
            set { customerProductIDField = value; }
        }

        /// <remarks/>
        public string SubstitutedProductID
        {
            get { return substitutedProductIDField; }
            set { substitutedProductIDField = value; }
        }

        /// <remarks/>
        public string ReplacedProductID
        {
            get { return replacedProductIDField; }
            set { replacedProductIDField = value; }
        }

        /// <remarks/>
        [XmlElement (DataType = "integer")]
        public string OrderQuantity
        {
            get { return orderQuantityField; }
            set { orderQuantityField = value; }
        }

        /// <remarks/>
        public string UnitOfMeasure
        {
            get { return unitOfMeasureField; }
            set { unitOfMeasureField = value; }
        }

        /// <remarks/>
        [XmlElement (DataType = "integer")]
        public string AcknowledgedQuantity
        {
            get { return acknowledgedQuantityField; }
            set { acknowledgedQuantityField = value; }
        }

        /// <remarks/>
        public string AcknowledgedUnitOfMeasure
        {
            get { return acknowledgedUnitOfMeasureField; }
            set { acknowledgedUnitOfMeasureField = value; }
        }

        /// <remarks/>
        public decimal SellPrice
        {
            get { return sellPriceField; }
            set { sellPriceField = value; }
        }

        /// <remarks/>
        public decimal AcknowledgedSellPrice
        {
            get { return acknowledgedSellPriceField; }
            set { acknowledgedSellPriceField = value; }
        }

        /// <remarks/>
        [XmlElement (DataType = "date")]
        public DateTime ScheduledToShipDate
        {
            get { return scheduledToShipDateField; }
            set { scheduledToShipDateField = value; }
        }

        /// <remarks/>
        [XmlIgnore]
        public bool ScheduledToShipDateSpecified
        {
            get { return scheduledToShipDateFieldSpecified; }
            set { scheduledToShipDateFieldSpecified = value; }
        }

        /// <remarks/>
        public string ItemRejectionMessage
        {
            get { return itemRejectionMessageField; }
            set { itemRejectionMessageField = value; }
        }
    }

    /// <remarks/>
    [Flags]
    [GeneratedCode ("xsd", "2.0.50727.3038")]
    [Serializable]
    [XmlType (AnonymousType = true)]
    [XmlRoot (Namespace = "", IsNullable = false)]
    public enum ItemAcknowledgmentType {
        /// <remarks/>
        AC = 1,

        /// <remarks/>
        IA = 2,

        /// <remarks/>
        IB = 4,

        /// <remarks/>
        IC = 8,

        /// <remarks/>
        IR = 16,
    }
}