//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5018
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 

namespace VitalChoice.Ecommerce.Domain.Entities.VeraCore.FilesSchema
{
    /// <remarks/>
    [GeneratedCode ("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory ("code")]
    [XmlType (AnonymousType = true)]
    [XmlRoot (Namespace = "", IsNullable = false)]
    public class ShipmentNotice {
        private string billOfLadingNumberField;
        private string companyIDField;
        private decimal freightAmountField;

        private string freightCarrierField;

        private string freightServiceField;
        private string fromField;

        private decimal grossWeightField;
        private string pickSlipIdField;
        private PurchaseOrderInformation[] purchaseOrderInformationField;
        private string sCACCodeField;

        private string sWSFreightCodeField;
        private string shipCommentField;

        private DateTime shipDateField;
        private ShipFromAddress shipFromAddressField;

        private DateTime shipTimeField;

        private bool shipTimeFieldSpecified;

        private ShipToAddress shipToAddressField;
        private string shipmentIDField;

        private string toField;
        private DateTime transactionDateField;

        private DateTime transactionTimeField;

        private bool transactionTimeFieldSpecified;
        private string vendorCustIDField;
        private string vendorIDField;

        /// <remarks/>
        public string VendorID
        {
            get { return vendorIDField; }
            set { vendorIDField = value; }
        }

        /// <remarks/>
        public string VendorCustID
        {
            get { return vendorCustIDField; }
            set { vendorCustIDField = value; }
        }

        /// <remarks/>
        public string CompanyID
        {
            get { return companyIDField; }
            set { companyIDField = value; }
        }

        /// <remarks/>
        [XmlElement (DataType = "integer")]
        public string ShipmentID
        {
            get { return shipmentIDField; }
            set { shipmentIDField = value; }
        }

        /// <remarks/>
        [XmlElement (DataType = "date")]
        public DateTime TransactionDate
        {
            get { return transactionDateField; }
            set { transactionDateField = value; }
        }

        /// <remarks/>
        [XmlElement (DataType = "time")]
        public DateTime TransactionTime
        {
            get { return transactionTimeField; }
            set { transactionTimeField = value; }
        }

        /// <remarks/>
        [XmlIgnore]
        public bool TransactionTimeSpecified
        {
            get { return transactionTimeFieldSpecified; }
            set { transactionTimeFieldSpecified = value; }
        }

        /// <remarks/>
        public string FreightCarrier
        {
            get { return freightCarrierField; }
            set { freightCarrierField = value; }
        }

        /// <remarks/>
        public string FreightService
        {
            get { return freightServiceField; }
            set { freightServiceField = value; }
        }

        /// <remarks/>
        public decimal GrossWeight
        {
            get { return grossWeightField; }
            set { grossWeightField = value; }
        }

        /// <remarks/>
        public string SWSFreightCode
        {
            get { return sWSFreightCodeField; }
            set { sWSFreightCodeField = value; }
        }

        /// <remarks/>
        public string BillOfLadingNumber
        {
            get { return billOfLadingNumberField; }
            set { billOfLadingNumberField = value; }
        }

        /// <remarks/>
        public decimal FreightAmount
        {
            get { return freightAmountField; }
            set { freightAmountField = value; }
        }

        /// <remarks/>
        [XmlElement (DataType = "date")]
        public DateTime ShipDate
        {
            get { return shipDateField; }
            set { shipDateField = value; }
        }

        /// <remarks/>
        [XmlElement (DataType = "time")]
        public DateTime ShipTime
        {
            get { return shipTimeField; }
            set { shipTimeField = value; }
        }

        /// <remarks/>
        [XmlIgnore]
        public bool ShipTimeSpecified
        {
            get { return shipTimeFieldSpecified; }
            set { shipTimeFieldSpecified = value; }
        }

        /// <remarks/>
        public string SCACCode
        {
            get { return sCACCodeField; }
            set { sCACCodeField = value; }
        }

        /// <remarks/>
        public string ShipComment
        {
            get { return shipCommentField; }
            set { shipCommentField = value; }
        }

        /// <remarks/>
        public string PickSlipId
        {
            get { return pickSlipIdField; }
            set { pickSlipIdField = value; }
        }

        /// <remarks/>
        public ShipToAddress ShipToAddress
        {
            get { return shipToAddressField; }
            set { shipToAddressField = value; }
        }

        /// <remarks/>
        public ShipFromAddress ShipFromAddress
        {
            get { return shipFromAddressField; }
            set { shipFromAddressField = value; }
        }

        /// <remarks/>
        [XmlElement ("PurchaseOrderInformation")]
        public PurchaseOrderInformation[] PurchaseOrderInformation
        {
            get { return purchaseOrderInformationField; }
            set { purchaseOrderInformationField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string From
        {
            get { return fromField; }
            set { fromField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string To
        {
            get { return toField; }
            set { toField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode ("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory ("code")]
    [XmlType (AnonymousType = true)]
    [XmlRoot (Namespace = "", IsNullable = false)]
    public class ShipToAddress {
        private string addressIDField;

        private string attentionField;

        private string cityField;

        private string countryCodeField;

        private string countryNameField;
        private string internationalStateField;
        private string line1Field;

        private string line2Field;
        private string nameField;
        private string postalCodeField;
        private string stateProvinceCodeField;

        /// <remarks/>
        public string AddressID
        {
            get { return addressIDField; }
            set { addressIDField = value; }
        }

        /// <remarks/>
        public string Name
        {
            get { return nameField; }
            set { nameField = value; }
        }

        /// <remarks/>
        public string Attention
        {
            get { return attentionField; }
            set { attentionField = value; }
        }

        /// <remarks/>
        public string Line1
        {
            get { return line1Field; }
            set { line1Field = value; }
        }

        /// <remarks/>
        public string Line2
        {
            get { return line2Field; }
            set { line2Field = value; }
        }

        /// <remarks/>
        public string City
        {
            get { return cityField; }
            set { cityField = value; }
        }

        /// <remarks/>
        public string StateProvinceCode
        {
            get { return stateProvinceCodeField; }
            set { stateProvinceCodeField = value; }
        }

        /// <remarks/>
        public string PostalCode
        {
            get { return postalCodeField; }
            set { postalCodeField = value; }
        }

        /// <remarks/>
        public string InternationalState
        {
            get { return internationalStateField; }
            set { internationalStateField = value; }
        }

        /// <remarks/>
        public string CountryCode
        {
            get { return countryCodeField; }
            set { countryCodeField = value; }
        }

        /// <remarks/>
        public string CountryName
        {
            get { return countryNameField; }
            set { countryNameField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode ("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory ("code")]
    [XmlType (AnonymousType = true)]
    [XmlRoot (Namespace = "", IsNullable = false)]
    public class ShipFromAddress {
        private string addressIDField;

        private string cityField;

        private string countryCodeField;

        private string countryNameField;
        private string internationalStateField;
        private string line1Field;

        private string line2Field;
        private string nameField;
        private string postalCodeField;
        private string stateProvinceCodeField;

        /// <remarks/>
        public string AddressID
        {
            get { return addressIDField; }
            set { addressIDField = value; }
        }

        /// <remarks/>
        public string Name
        {
            get { return nameField; }
            set { nameField = value; }
        }

        /// <remarks/>
        public string Line1
        {
            get { return line1Field; }
            set { line1Field = value; }
        }

        /// <remarks/>
        public string Line2
        {
            get { return line2Field; }
            set { line2Field = value; }
        }

        /// <remarks/>
        public string City
        {
            get { return cityField; }
            set { cityField = value; }
        }

        /// <remarks/>
        public string StateProvinceCode
        {
            get { return stateProvinceCodeField; }
            set { stateProvinceCodeField = value; }
        }

        /// <remarks/>
        public string PostalCode
        {
            get { return postalCodeField; }
            set { postalCodeField = value; }
        }

        /// <remarks/>
        public string InternationalState
        {
            get { return internationalStateField; }
            set { internationalStateField = value; }
        }

        /// <remarks/>
        public string CountryCode
        {
            get { return countryCodeField; }
            set { countryCodeField = value; }
        }

        /// <remarks/>
        public string CountryName
        {
            get { return countryNameField; }
            set { countryNameField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode ("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory ("code")]
    [XmlType (AnonymousType = true)]
    [XmlRoot (Namespace = "", IsNullable = false)]
    public class PurchaseOrderInformation {
        private string customerPurchaseOrderNumberField;

        private ItemInformation[] itemInformationField;
        private string purchaseOrderNumberField;
        private ShipToAddress shipToAddressField;

        /// <remarks/>
        public string PurchaseOrderNumber
        {
            get { return purchaseOrderNumberField; }
            set { purchaseOrderNumberField = value; }
        }

        /// <remarks/>
        public string CustomerPurchaseOrderNumber
        {
            get { return customerPurchaseOrderNumberField; }
            set { customerPurchaseOrderNumberField = value; }
        }

        /// <remarks/>
        public ShipToAddress ShipToAddress
        {
            get { return shipToAddressField; }
            set { shipToAddressField = value; }
        }

        /// <remarks/>
        [XmlElement ("ItemInformation")]
        public ItemInformation[] ItemInformation
        {
            get { return itemInformationField; }
            set { itemInformationField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode ("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory ("code")]
    [XmlType (AnonymousType = true)]
    [XmlRoot (Namespace = "", IsNullable = false)]
    public class ItemInformation {
        private string customerProductIDField;
        private LabelInformation labelInformationField;
        private string lineNumberField;

        private string quantityShippedField;

        private string unitOfMeasureField;
        private string vendorProductIDField;

        /// <remarks/>
        [XmlElement (DataType = "integer")]
        public string LineNumber
        {
            get { return lineNumberField; }
            set { lineNumberField = value; }
        }

        /// <remarks/>
        public string VendorProductID
        {
            get { return vendorProductIDField; }
            set { vendorProductIDField = value; }
        }

        /// <remarks/>
        public string CustomerProductID
        {
            get { return customerProductIDField; }
            set { customerProductIDField = value; }
        }

        /// <remarks/>
        [XmlElement (DataType = "integer")]
        public string QuantityShipped
        {
            get { return quantityShippedField; }
            set { quantityShippedField = value; }
        }

        /// <remarks/>
        public string UnitOfMeasure
        {
            get { return unitOfMeasureField; }
            set { unitOfMeasureField = value; }
        }

        /// <remarks/>
        public LabelInformation LabelInformation
        {
            get { return labelInformationField; }
            set { labelInformationField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode ("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory ("code")]
    [XmlType (AnonymousType = true)]
    [XmlRoot (Namespace = "", IsNullable = false)]
    public class LabelInformation {
        private string labelTrackingNumberField;

        /// <remarks/>
        public string LabelTrackingNumber
        {
            get { return labelTrackingNumberField; }
            set { labelTrackingNumberField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode ("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory ("code")]
    [XmlType (AnonymousType = true)]
    [XmlRoot (Namespace = "", IsNullable = false)]
    public class SerialNumbers {
        private string snField;

        /// <remarks/>
        public string SN
        {
            get { return snField; }
            set { snField = value; }
        }
    }
}