//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

namespace VitalChoice.Ecommerce.Domain.Entities.VeraCore.FilesSchema
{
    /// <remarks/>
    [GeneratedCode ("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory ("code")]
    [XmlType (AnonymousType = true)]
    [XmlRoot (Namespace = "", IsNullable = false)]
    public class CancelAck {
        private string canceledCompleteField;
        private string orderIDField;

        /// <remarks/>
        public string OrderID
        {
            get { return orderIDField; }
            set { orderIDField = value; }
        }

        /// <remarks/>
        public string CanceledComplete
        {
            get { return canceledCompleteField; }
            set { canceledCompleteField = value; }
        }
    }
}