//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class LookupValue
{
	public virtual int idLookup
	{
		get;
		set;
	}

	public virtual int id
	{
		get;
		set;
	}

	public virtual string Value
	{
		get;
		set;
	}

	public virtual Lookup Lookup
	{
		get;
		set;
	}

}

