//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class OptionType
{
	public virtual string Name
	{
		get;
		set;
	}

	public virtual string CategoryName
	{
		get;
		set;
	}

	public virtual string TypeName
	{
		get;
		set;
	}

	public virtual int id
	{
		get;
		set;
	}

	public virtual bool IsSkuPrivate
	{
		get;
		set;
	}

}

