//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Shipping : IAction
{
	public virtual Total Total
	{
		get;
		set;
	}

	public virtual decimal Execute(object Context)
	{
		throw new System.NotImplementedException();
	}

}

