//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Sku
{
	public virtual int idProduct
	{
		get;
		set;
	}

	public virtual int id
	{
		get;
		set;
	}

	public virtual Product Product
	{
		get;
		set;
	}

	public virtual IEnumerable<OptionValue> Option
	{
		get;
		set;
	}

}

