//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;

public class Total : IAction
{
	public virtual object Context
	{
		get;
		set;
	}

	public virtual string[] InputDependencyNames
	{
		get;
		set;
	}

	public virtual string OutputDependencyNames
	{
		get;
		set;
	}

	public virtual decimal Execute(object Context)
	{
	    decimal result = 0;
	    foreach (var name in InputDependencyNames)
	    {
            result += Container.Resolve<IAction>(name).Execute();
	    }
	    return result;
	}

}

