//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TypeCategories
{
	public virtual int idProductType
	{
		get;
		set;
	}

	public virtual int idCategory
	{
		get;
		set;
	}

	public virtual Category Category
	{
		get;
		set;
	}

	public virtual ProductType ProductType
	{
		get;
		set;
	}

}

