//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitalChoice.Business.FedEx.Locator
{
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fedex.com/ws/locator/v2", ConfigurationName="VitalChoice.Business.FedEx.Locator.LocatorPortType")]
    public interface LocatorPortType
    {
        
        // CODEGEN: Generating message contract since the operation fedExLocator is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="fedExLocator", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VitalChoice.Business.FedEx.Locator.fedExLocatorResponse fedExLocator(VitalChoice.Business.FedEx.Locator.fedExLocatorRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="fedExLocator", ReplyAction="*")]
        System.Threading.Tasks.Task<VitalChoice.Business.FedEx.Locator.fedExLocatorResponse> fedExLocatorAsync(VitalChoice.Business.FedEx.Locator.fedExLocatorRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/locator/v2")]
    public partial class FedExLocatorRequest
    {
        
        private WebAuthenticationDetail webAuthenticationDetailField;
        
        private ClientDetail clientDetailField;
        
        private TransactionDetail transactionDetailField;
        
        private VersionId versionField;
        
        private int beginningRecordIndexField;
        
        private bool beginningRecordIndexFieldSpecified;
        
        private string maximumMatchCountField;
        
        private DistanceUnits distanceUnitsField;
        
        private bool distanceUnitsFieldSpecified;
        
        private string nearToPhoneNumberField;
        
        private Address nearToAddressField;
        
        private DropoffServicesDesired dropoffServicesDesiredField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public WebAuthenticationDetail WebAuthenticationDetail
        {
            get
            {
                return this.webAuthenticationDetailField;
            }
            set
            {
                this.webAuthenticationDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ClientDetail ClientDetail
        {
            get
            {
                return this.clientDetailField;
            }
            set
            {
                this.clientDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TransactionDetail TransactionDetail
        {
            get
            {
                return this.transactionDetailField;
            }
            set
            {
                this.transactionDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public VersionId Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int BeginningRecordIndex
        {
            get
            {
                return this.beginningRecordIndexField;
            }
            set
            {
                this.beginningRecordIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BeginningRecordIndexSpecified
        {
            get
            {
                return this.beginningRecordIndexFieldSpecified;
            }
            set
            {
                this.beginningRecordIndexFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=5)]
        public string MaximumMatchCount
        {
            get
            {
                return this.maximumMatchCountField;
            }
            set
            {
                this.maximumMatchCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public DistanceUnits DistanceUnits
        {
            get
            {
                return this.distanceUnitsField;
            }
            set
            {
                this.distanceUnitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DistanceUnitsSpecified
        {
            get
            {
                return this.distanceUnitsFieldSpecified;
            }
            set
            {
                this.distanceUnitsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string NearToPhoneNumber
        {
            get
            {
                return this.nearToPhoneNumberField;
            }
            set
            {
                this.nearToPhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Address NearToAddress
        {
            get
            {
                return this.nearToAddressField;
            }
            set
            {
                this.nearToAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public DropoffServicesDesired DropoffServicesDesired
        {
            get
            {
                return this.dropoffServicesDesiredField;
            }
            set
            {
                this.dropoffServicesDesiredField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/locator/v2")]
    public partial class WebAuthenticationDetail
    {
        
        private WebAuthenticationCredential userCredentialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public WebAuthenticationCredential UserCredential
        {
            get
            {
                return this.userCredentialField;
            }
            set
            {
                this.userCredentialField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/locator/v2")]
    public partial class WebAuthenticationCredential
    {
        
        private string keyField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/locator/v2")]
    public partial class DropoffLocationProfile
    {
        
        private bool expressServiceField;
        
        private bool expressServiceFieldSpecified;
        
        private bool groundServiceField;
        
        private bool groundServiceFieldSpecified;
        
        private string hoursWeekdaysField;
        
        private string hoursSaturdaysField;
        
        private string lastExpressDropoffTimeWeekdaysField;
        
        private string lastExpressDropoffTimeSaturdaysField;
        
        private string lastGroundDropoffTimeWeekdaysField;
        
        private string lastGroundDropoffTimeSaturdaysField;
        
        private bool holdAtLocationField;
        
        private bool holdAtLocationFieldSpecified;
        
        private bool groundHoldAtLocationField;
        
        private bool groundHoldAtLocationFieldSpecified;
        
        private bool dangerousGoodsField;
        
        private bool dangerousGoodsFieldSpecified;
        
        private bool packagingSuppliesField;
        
        private bool packagingSuppliesFieldSpecified;
        
        private bool packagingServicesField;
        
        private bool packagingServicesFieldSpecified;
        
        private bool returnSystemField;
        
        private bool returnSystemFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool ExpressService
        {
            get
            {
                return this.expressServiceField;
            }
            set
            {
                this.expressServiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpressServiceSpecified
        {
            get
            {
                return this.expressServiceFieldSpecified;
            }
            set
            {
                this.expressServiceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool GroundService
        {
            get
            {
                return this.groundServiceField;
            }
            set
            {
                this.groundServiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GroundServiceSpecified
        {
            get
            {
                return this.groundServiceFieldSpecified;
            }
            set
            {
                this.groundServiceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string HoursWeekdays
        {
            get
            {
                return this.hoursWeekdaysField;
            }
            set
            {
                this.hoursWeekdaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string HoursSaturdays
        {
            get
            {
                return this.hoursSaturdaysField;
            }
            set
            {
                this.hoursSaturdaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LastExpressDropoffTimeWeekdays
        {
            get
            {
                return this.lastExpressDropoffTimeWeekdaysField;
            }
            set
            {
                this.lastExpressDropoffTimeWeekdaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LastExpressDropoffTimeSaturdays
        {
            get
            {
                return this.lastExpressDropoffTimeSaturdaysField;
            }
            set
            {
                this.lastExpressDropoffTimeSaturdaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string LastGroundDropoffTimeWeekdays
        {
            get
            {
                return this.lastGroundDropoffTimeWeekdaysField;
            }
            set
            {
                this.lastGroundDropoffTimeWeekdaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string LastGroundDropoffTimeSaturdays
        {
            get
            {
                return this.lastGroundDropoffTimeSaturdaysField;
            }
            set
            {
                this.lastGroundDropoffTimeSaturdaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool HoldAtLocation
        {
            get
            {
                return this.holdAtLocationField;
            }
            set
            {
                this.holdAtLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HoldAtLocationSpecified
        {
            get
            {
                return this.holdAtLocationFieldSpecified;
            }
            set
            {
                this.holdAtLocationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool GroundHoldAtLocation
        {
            get
            {
                return this.groundHoldAtLocationField;
            }
            set
            {
                this.groundHoldAtLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GroundHoldAtLocationSpecified
        {
            get
            {
                return this.groundHoldAtLocationFieldSpecified;
            }
            set
            {
                this.groundHoldAtLocationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool DangerousGoods
        {
            get
            {
                return this.dangerousGoodsField;
            }
            set
            {
                this.dangerousGoodsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DangerousGoodsSpecified
        {
            get
            {
                return this.dangerousGoodsFieldSpecified;
            }
            set
            {
                this.dangerousGoodsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool PackagingSupplies
        {
            get
            {
                return this.packagingSuppliesField;
            }
            set
            {
                this.packagingSuppliesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PackagingSuppliesSpecified
        {
            get
            {
                return this.packagingSuppliesFieldSpecified;
            }
            set
            {
                this.packagingSuppliesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool PackagingServices
        {
            get
            {
                return this.packagingServicesField;
            }
            set
            {
                this.packagingServicesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PackagingServicesSpecified
        {
            get
            {
                return this.packagingServicesFieldSpecified;
            }
            set
            {
                this.packagingServicesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool ReturnSystem
        {
            get
            {
                return this.returnSystemField;
            }
            set
            {
                this.returnSystemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReturnSystemSpecified
        {
            get
            {
                return this.returnSystemFieldSpecified;
            }
            set
            {
                this.returnSystemFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/locator/v2")]
    public partial class Distance
    {
        
        private decimal valueField;
        
        private DistanceUnits unitsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public DistanceUnits Units
        {
            get
            {
                return this.unitsField;
            }
            set
            {
                this.unitsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/locator/v2")]
    public enum DistanceUnits
    {
        
        /// <remarks/>
        KM,
        
        /// <remarks/>
        MI,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/locator/v2")]
    public partial class DropoffLocation
    {
        
        private string businessNameField;
        
        private string businessIdField;
        
        private string businessDescriptionField;
        
        private Address businessAddressField;
        
        private Distance distanceField;
        
        private DropoffLocationProfile serviceProfileField;
        
        private string recordIndexField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BusinessName
        {
            get
            {
                return this.businessNameField;
            }
            set
            {
                this.businessNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BusinessId
        {
            get
            {
                return this.businessIdField;
            }
            set
            {
                this.businessIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BusinessDescription
        {
            get
            {
                return this.businessDescriptionField;
            }
            set
            {
                this.businessDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Address BusinessAddress
        {
            get
            {
                return this.businessAddressField;
            }
            set
            {
                this.businessAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Distance Distance
        {
            get
            {
                return this.distanceField;
            }
            set
            {
                this.distanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public DropoffLocationProfile ServiceProfile
        {
            get
            {
                return this.serviceProfileField;
            }
            set
            {
                this.serviceProfileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=6)]
        public string RecordIndex
        {
            get
            {
                return this.recordIndexField;
            }
            set
            {
                this.recordIndexField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/locator/v2")]
    public partial class Address
    {
        
        private string[] streetLinesField;
        
        private string cityField;
        
        private string stateOrProvinceCodeField;
        
        private string postalCodeField;
        
        private string urbanizationCodeField;
        
        private string countryCodeField;
        
        private bool residentialField;
        
        private bool residentialFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StreetLines", Order=0)]
        public string[] StreetLines
        {
            get
            {
                return this.streetLinesField;
            }
            set
            {
                this.streetLinesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StateOrProvinceCode
        {
            get
            {
                return this.stateOrProvinceCodeField;
            }
            set
            {
                this.stateOrProvinceCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string UrbanizationCode
        {
            get
            {
                return this.urbanizationCodeField;
            }
            set
            {
                this.urbanizationCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CountryCode
        {
            get
            {
                return this.countryCodeField;
            }
            set
            {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool Residential
        {
            get
            {
                return this.residentialField;
            }
            set
            {
                this.residentialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResidentialSpecified
        {
            get
            {
                return this.residentialFieldSpecified;
            }
            set
            {
                this.residentialFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/locator/v2")]
    public partial class NotificationParameter
    {
        
        private string idField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/locator/v2")]
    public partial class Notification
    {
        
        private NotificationSeverityType severityField;
        
        private string sourceField;
        
        private string codeField;
        
        private string messageField;
        
        private string localizedMessageField;
        
        private NotificationParameter[] messageParametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NotificationSeverityType Severity
        {
            get
            {
                return this.severityField;
            }
            set
            {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LocalizedMessage
        {
            get
            {
                return this.localizedMessageField;
            }
            set
            {
                this.localizedMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MessageParameters", Order=5)]
        public NotificationParameter[] MessageParameters
        {
            get
            {
                return this.messageParametersField;
            }
            set
            {
                this.messageParametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/locator/v2")]
    public enum NotificationSeverityType
    {
        
        /// <remarks/>
        ERROR,
        
        /// <remarks/>
        FAILURE,
        
        /// <remarks/>
        NOTE,
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        WARNING,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/locator/v2")]
    public partial class FedExLocatorReply
    {
        
        private NotificationSeverityType highestSeverityField;
        
        private Notification[] notificationsField;
        
        private TransactionDetail transactionDetailField;
        
        private VersionId versionField;
        
        private DropoffLocation[] dropoffLocationsField;
        
        private int availableRecordCountField;
        
        private bool availableRecordCountFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NotificationSeverityType HighestSeverity
        {
            get
            {
                return this.highestSeverityField;
            }
            set
            {
                this.highestSeverityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Notifications", Order=1)]
        public Notification[] Notifications
        {
            get
            {
                return this.notificationsField;
            }
            set
            {
                this.notificationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TransactionDetail TransactionDetail
        {
            get
            {
                return this.transactionDetailField;
            }
            set
            {
                this.transactionDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public VersionId Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DropoffLocations", Order=4)]
        public DropoffLocation[] DropoffLocations
        {
            get
            {
                return this.dropoffLocationsField;
            }
            set
            {
                this.dropoffLocationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int AvailableRecordCount
        {
            get
            {
                return this.availableRecordCountField;
            }
            set
            {
                this.availableRecordCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AvailableRecordCountSpecified
        {
            get
            {
                return this.availableRecordCountFieldSpecified;
            }
            set
            {
                this.availableRecordCountFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/locator/v2")]
    public partial class TransactionDetail
    {
        
        private string customerTransactionIdField;
        
        private Localization localizationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomerTransactionId
        {
            get
            {
                return this.customerTransactionIdField;
            }
            set
            {
                this.customerTransactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Localization Localization
        {
            get
            {
                return this.localizationField;
            }
            set
            {
                this.localizationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/locator/v2")]
    public partial class Localization
    {
        
        private string languageCodeField;
        
        private string localeCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LanguageCode
        {
            get
            {
                return this.languageCodeField;
            }
            set
            {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LocaleCode
        {
            get
            {
                return this.localeCodeField;
            }
            set
            {
                this.localeCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/locator/v2")]
    public partial class VersionId
    {
        
        private string serviceIdField;
        
        private int majorField;
        
        private int intermediateField;
        
        private int minorField;
        
        public VersionId()
        {
            this.serviceIdField = "dloc";
            this.majorField = 2;
            this.intermediateField = 0;
            this.minorField = 0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ServiceId
        {
            get
            {
                return this.serviceIdField;
            }
            set
            {
                this.serviceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Major
        {
            get
            {
                return this.majorField;
            }
            set
            {
                this.majorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Intermediate
        {
            get
            {
                return this.intermediateField;
            }
            set
            {
                this.intermediateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Minor
        {
            get
            {
                return this.minorField;
            }
            set
            {
                this.minorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/locator/v2")]
    public partial class DropoffServicesDesired
    {
        
        private bool expressField;
        
        private bool expressFieldSpecified;
        
        private bool groundField;
        
        private bool groundFieldSpecified;
        
        private bool fedExStaffedField;
        
        private bool fedExStaffedFieldSpecified;
        
        private bool fedExSelfServiceField;
        
        private bool fedExSelfServiceFieldSpecified;
        
        private bool fedExAuthorizedShippingCenterField;
        
        private bool fedExAuthorizedShippingCenterFieldSpecified;
        
        private bool latestExpressDropoffField;
        
        private bool latestExpressDropoffFieldSpecified;
        
        private System.DateTime expressDropoffAfterTimeField;
        
        private bool expressDropoffAfterTimeFieldSpecified;
        
        private bool holdAtLocationField;
        
        private bool holdAtLocationFieldSpecified;
        
        private bool groundHoldAtLocationField;
        
        private bool groundHoldAtLocationFieldSpecified;
        
        private bool dangerousGoodsField;
        
        private bool dangerousGoodsFieldSpecified;
        
        private bool saturdayServiceField;
        
        private bool saturdayServiceFieldSpecified;
        
        private bool packingSuppliesField;
        
        private bool packingSuppliesFieldSpecified;
        
        private bool packingServicesField;
        
        private bool packingServicesFieldSpecified;
        
        private bool returnSystemField;
        
        private bool returnSystemFieldSpecified;
        
        private RedirectToHoldLocationType redirectToHoldLocationField;
        
        private bool redirectToHoldLocationFieldSpecified;
        
        private bool searchSameStateOnlyField;
        
        private bool searchSameStateOnlyFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Express
        {
            get
            {
                return this.expressField;
            }
            set
            {
                this.expressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpressSpecified
        {
            get
            {
                return this.expressFieldSpecified;
            }
            set
            {
                this.expressFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool Ground
        {
            get
            {
                return this.groundField;
            }
            set
            {
                this.groundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GroundSpecified
        {
            get
            {
                return this.groundFieldSpecified;
            }
            set
            {
                this.groundFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool FedExStaffed
        {
            get
            {
                return this.fedExStaffedField;
            }
            set
            {
                this.fedExStaffedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FedExStaffedSpecified
        {
            get
            {
                return this.fedExStaffedFieldSpecified;
            }
            set
            {
                this.fedExStaffedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool FedExSelfService
        {
            get
            {
                return this.fedExSelfServiceField;
            }
            set
            {
                this.fedExSelfServiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FedExSelfServiceSpecified
        {
            get
            {
                return this.fedExSelfServiceFieldSpecified;
            }
            set
            {
                this.fedExSelfServiceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool FedExAuthorizedShippingCenter
        {
            get
            {
                return this.fedExAuthorizedShippingCenterField;
            }
            set
            {
                this.fedExAuthorizedShippingCenterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FedExAuthorizedShippingCenterSpecified
        {
            get
            {
                return this.fedExAuthorizedShippingCenterFieldSpecified;
            }
            set
            {
                this.fedExAuthorizedShippingCenterFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool LatestExpressDropoff
        {
            get
            {
                return this.latestExpressDropoffField;
            }
            set
            {
                this.latestExpressDropoffField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatestExpressDropoffSpecified
        {
            get
            {
                return this.latestExpressDropoffFieldSpecified;
            }
            set
            {
                this.latestExpressDropoffFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time", Order=6)]
        public System.DateTime ExpressDropoffAfterTime
        {
            get
            {
                return this.expressDropoffAfterTimeField;
            }
            set
            {
                this.expressDropoffAfterTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpressDropoffAfterTimeSpecified
        {
            get
            {
                return this.expressDropoffAfterTimeFieldSpecified;
            }
            set
            {
                this.expressDropoffAfterTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool HoldAtLocation
        {
            get
            {
                return this.holdAtLocationField;
            }
            set
            {
                this.holdAtLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HoldAtLocationSpecified
        {
            get
            {
                return this.holdAtLocationFieldSpecified;
            }
            set
            {
                this.holdAtLocationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool GroundHoldAtLocation
        {
            get
            {
                return this.groundHoldAtLocationField;
            }
            set
            {
                this.groundHoldAtLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GroundHoldAtLocationSpecified
        {
            get
            {
                return this.groundHoldAtLocationFieldSpecified;
            }
            set
            {
                this.groundHoldAtLocationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool DangerousGoods
        {
            get
            {
                return this.dangerousGoodsField;
            }
            set
            {
                this.dangerousGoodsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DangerousGoodsSpecified
        {
            get
            {
                return this.dangerousGoodsFieldSpecified;
            }
            set
            {
                this.dangerousGoodsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool SaturdayService
        {
            get
            {
                return this.saturdayServiceField;
            }
            set
            {
                this.saturdayServiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SaturdayServiceSpecified
        {
            get
            {
                return this.saturdayServiceFieldSpecified;
            }
            set
            {
                this.saturdayServiceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool PackingSupplies
        {
            get
            {
                return this.packingSuppliesField;
            }
            set
            {
                this.packingSuppliesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PackingSuppliesSpecified
        {
            get
            {
                return this.packingSuppliesFieldSpecified;
            }
            set
            {
                this.packingSuppliesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool PackingServices
        {
            get
            {
                return this.packingServicesField;
            }
            set
            {
                this.packingServicesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PackingServicesSpecified
        {
            get
            {
                return this.packingServicesFieldSpecified;
            }
            set
            {
                this.packingServicesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool ReturnSystem
        {
            get
            {
                return this.returnSystemField;
            }
            set
            {
                this.returnSystemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReturnSystemSpecified
        {
            get
            {
                return this.returnSystemFieldSpecified;
            }
            set
            {
                this.returnSystemFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public RedirectToHoldLocationType RedirectToHoldLocation
        {
            get
            {
                return this.redirectToHoldLocationField;
            }
            set
            {
                this.redirectToHoldLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RedirectToHoldLocationSpecified
        {
            get
            {
                return this.redirectToHoldLocationFieldSpecified;
            }
            set
            {
                this.redirectToHoldLocationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool SearchSameStateOnly
        {
            get
            {
                return this.searchSameStateOnlyField;
            }
            set
            {
                this.searchSameStateOnlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SearchSameStateOnlySpecified
        {
            get
            {
                return this.searchSameStateOnlyFieldSpecified;
            }
            set
            {
                this.searchSameStateOnlyFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/locator/v2")]
    public enum RedirectToHoldLocationType
    {
        
        /// <remarks/>
        EXPRESS,
        
        /// <remarks/>
        GROUND,
        
        /// <remarks/>
        HOMEDELIVERY,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/locator/v2")]
    public partial class ClientDetail
    {
        
        private string accountNumberField;
        
        private string meterNumberField;
        
        private Localization localizationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MeterNumber
        {
            get
            {
                return this.meterNumberField;
            }
            set
            {
                this.meterNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Localization Localization
        {
            get
            {
                return this.localizationField;
            }
            set
            {
                this.localizationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fedExLocatorRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fedex.com/ws/locator/v2", Order=0)]
        public VitalChoice.Business.FedEx.Locator.FedExLocatorRequest FedExLocatorRequest;
        
        public fedExLocatorRequest1()
        {
        }
        
        public fedExLocatorRequest1(VitalChoice.Business.FedEx.Locator.FedExLocatorRequest FedExLocatorRequest)
        {
            this.FedExLocatorRequest = FedExLocatorRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fedExLocatorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fedex.com/ws/locator/v2", Order=0)]
        public VitalChoice.Business.FedEx.Locator.FedExLocatorReply FedExLocatorReply;
        
        public fedExLocatorResponse()
        {
        }
        
        public fedExLocatorResponse(VitalChoice.Business.FedEx.Locator.FedExLocatorReply FedExLocatorReply)
        {
            this.FedExLocatorReply = FedExLocatorReply;
        }
    }
    
    public interface LocatorPortTypeChannel : VitalChoice.Business.FedEx.Locator.LocatorPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    public partial class LocatorPortTypeClient : System.ServiceModel.ClientBase<VitalChoice.Business.FedEx.Locator.LocatorPortType>, VitalChoice.Business.FedEx.Locator.LocatorPortType
    {
        
        public LocatorPortTypeClient()
        {
        }
        
        public LocatorPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public LocatorPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public LocatorPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public LocatorPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VitalChoice.Business.FedEx.Locator.fedExLocatorResponse VitalChoice.Business.FedEx.Locator.LocatorPortType.fedExLocator(VitalChoice.Business.FedEx.Locator.fedExLocatorRequest1 request)
        {
            return base.Channel.fedExLocator(request);
        }
        
        public VitalChoice.Business.FedEx.Locator.FedExLocatorReply fedExLocator(VitalChoice.Business.FedEx.Locator.FedExLocatorRequest FedExLocatorRequest)
        {
            VitalChoice.Business.FedEx.Locator.fedExLocatorRequest1 inValue = new VitalChoice.Business.FedEx.Locator.fedExLocatorRequest1();
            inValue.FedExLocatorRequest = FedExLocatorRequest;
            VitalChoice.Business.FedEx.Locator.fedExLocatorResponse retVal = ((VitalChoice.Business.FedEx.Locator.LocatorPortType)(this)).fedExLocator(inValue);
            return retVal.FedExLocatorReply;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VitalChoice.Business.FedEx.Locator.fedExLocatorResponse> VitalChoice.Business.FedEx.Locator.LocatorPortType.fedExLocatorAsync(VitalChoice.Business.FedEx.Locator.fedExLocatorRequest1 request)
        {
            return base.Channel.fedExLocatorAsync(request);
        }
        
        public System.Threading.Tasks.Task<VitalChoice.Business.FedEx.Locator.fedExLocatorResponse> fedExLocatorAsync(VitalChoice.Business.FedEx.Locator.FedExLocatorRequest FedExLocatorRequest)
        {
            VitalChoice.Business.FedEx.Locator.fedExLocatorRequest1 inValue = new VitalChoice.Business.FedEx.Locator.fedExLocatorRequest1();
            inValue.FedExLocatorRequest = FedExLocatorRequest;
            return ((VitalChoice.Business.FedEx.Locator.LocatorPortType)(this)).fedExLocatorAsync(inValue);
        }
    }
}