'use strict';

angular.module('app.dataAccess', [
	'app.core.dataAccess.services.infrastructureService',
	'app.core.dataAccess.services.userService',
	'app.core.dataAccess.services.contentService',
	'app.core.dataAccess.services.settingService',
	'app.core.dataAccess.services.authenticationService',
	'app.core.dataAccess.services.productService',
	'app.core.dataAccess.services.discountService',
	'app.core.dataAccess.services.fileService',
	'app.core.dataAccess.services.profileService',
	'app.core.dataAccess.services.gcService',
	'app.core.dataAccess.services.paymentMethodService',
	'app.core.dataAccess.services.orderNoteService',
	'app.core.dataAccess.services.customerService',
	'app.core.dataAccess.services.orderService',
	'app.core.dataAccess.services.affiliateService',
	'app.core.dataAccess.services.helpService',
	'app.core.dataAccess.services.promotionService',
	'app.core.dataAccess.services.contentAreaService',
	'app.core.dataAccess.services.manageStylesService',
	'app.core.dataAccess.services.vitalGreenService',
	'app.core.dataAccess.services.healthwiseService',
	'app.core.dataAccess.services.redirectService',
    'app.core.dataAccess.services.cacheService',
    'app.core.dataAccess.services.inventorySkuService',
    'app.core.dataAccess.services.serviceCodeService',
    'app.core.dataAccess.services.templateService',
    'app.core.dataAccess.services.monitorService',
    'app.core.dataAccess.services.publicService'
]);